/* ───────────────────────────────────────────────────────────
   文件: avatar_style_data.js
   功能: 旧版游戏入口使用的角色头像颜色与简称标签。
   说明: 必须在 game.js 之前加载，向 window 暴露 AVATAR_STYLES。
   ⚠️ 只放头像展示静态数据；不要在这里添加运行时逻辑。
   ─────────────────────────────────────────────────────────── */

var AVATAR_STYLES = {
  "玛伦": { color: "#4A5568", label: "玛" },
  "祁恩": { color: "#35234A", label: "祁" },
  "合唱团长": { color: "#7FA7D8", label: "唱" },
  "安柠": { color: "#7B5A37", label: "安" },
  "诺伊": { color: "#8A6A3A", label: "诺" },
  "母亲": { color: "#A68A5A", label: "母" },
  "卡戎": { color: "#5B1D24", label: "断" },
  "瑟萝弥": { color: "#4A3542", label: "弥" },
  "宁溯": { color: "#5D7E94", label: "宁" },
  "母亲的残响": { color: "#7FB5E7", label: "响" },
  "看塔仪": { color: "#8ECDE8", label: "塔" },
  "沈知微": { color: "#8A2F3A", label: "沈" },
  "珏衡": { color: "#C9CDD7", label: "衡" },
  "温别克": { color: "#80725E", label: "温" },
  "柏舟": { color: "#8A7B5C", label: "柏" },
  "行政人员": { color: "#A69778", label: "登" },
  "零四": { color: "#B08A32", label: "04" },
  "零七": { color: "#8F6B4A", label: "07" },
  "赤": { color: "#A33A2A", label: "赤" },
  "屿": { color: "#6F5A48", label: "屿" },
  "阿棠": { color: "#8A5A42", label: "棠" },
  "莫洛": { color: "#5A2430", label: "莫" },
  "黑暗巡演残部": { color: "#5B1D24", label: "残" },
  "伊莱娜": { color: "#596170", label: "稽" },
  "希声": { color: "#A4A9B6", label: "希" },
  "岐": { color: "#6D4D35", label: "岐" },
  "岚": { color: "#596A8C", label: "岚" },
  "玄鸦": { color: "#2B2D36", label: "玄" },
  "辞照": { color: "#8D86C9", label: "辞" },
  "初响会": { color: "#C9CDD7", label: "初" },
  "残留噬响体": { color: "#B89B6A", label: "噬" },
  "安娜": { color: "#8EC5FF", label: "安" },
  "侍从": { color: "#7C8796", label: "侍" },
  "永寂城": { color: "#9EC6E8", label: "寂" },
  "老雪": { color: "#7A8791", label: "雪" },
  "苏婆": { color: "#A56B3F", label: "苏" },
  "阿雁": { color: "#A15D3A", label: "雁" },
  "阿霜": { color: "#5D7185", label: "霜" },
  "老锔": { color: "#8B6748", label: "锔" },
  "阿柳": { color: "#748E68", label: "柳" },
  "破": { color: "#6E4035", label: "破" },
  "雪原游荡者": { color: "#65594E", label: "游" },
  "霜隘镇民": { color: "#9A7958", label: "镇" },
  "霜隘镇孩子": { color: "#C79A56", label: "童" },
  "零一": { color: "#B75D35", label: "01" },
  "琉璃": { color: "#B75D35", label: "璃" },
  "小雀": { color: "#D58A3A", label: "雀" },
  "卓玛": { color: "#C06B2C", label: "卓" },
  "风铃": { color: "#D6A54B", label: "铃" },
  "沉月": { color: "#8C6848", label: "月" },
  "孩子们": { color: "#CDA766", label: "童" },
  "崔敬": { color: "#4E5668", label: "崔" },
  "莫言书": { color: "#6F5A48", label: "言" },
  "青禾": { color: "#4E8A72", label: "青" },
  "扶苏": { color: "#C28A32", label: "扶" },
  "老院监": { color: "#9A8F78", label: "院" },
  "老纪": { color: "#716554", label: "纪" },
  "关婶": { color: "#A46F45", label: "关" },
  "礼堂卫队": { color: "#A69778", label: "卫" },
  "年轻卫队员": { color: "#B5A46A", label: "青" },
  "资深队员": { color: "#6E7480", label: "队" },
  "乌鸦先生": { color: "#34313A", label: "鸦" },
  "米拉奶奶": { color: "#8B7660", label: "米" },
  "白栖": { color: "#667085", label: "栖" },
  "霍尔特": { color: "#6A5C4B", label: "霍" },
  "奥托": { color: "#8A6D3F", label: "灯" },
  "琳": { color: "#7C5F8F", label: "琳" },
  "铃": { color: "#7C5F8F", label: "铃" },
  "伊莱娜": { color: "#596170", label: "伊" },
  "缇雅": { color: "#8E4AA8", label: "缇" },
  "阿缇娅": { color: "#A86A18", label: "暮" },
  "弥洛": { color: "#4E5D72", label: "低" },
  "槐序": { color: "#C49A45", label: "槐" },
  "洛温": { color: "#5A3728", label: "洛" },
  "伊芙白": { color: "#1F5F9C", label: "白" },
  "明弦": { color: "#B8233A", label: "明" }
};
